blank_issues_enabled: false
contact_links:
  - name: Check Language File Discussions
    url: https://github.com/Timthreetwelve/CheckLanguageFile/discussions
    about: If you have a question or some feedback, start a discussion. 
